#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Draw the bundled default avatar.

Shipped as an image rather than generated at runtime because both halves want the
same file: the card renderer stamps it on every card and the browser half shows it in
the header chip. Generated by a script so it is reproducible (and so nobody has to
wonder where a 256×256 PNG in an `assets/` directory came from).

The mark is a prompt: `>` and a cursor, on a deep blue gradient disc. It stays legible
at 22px (the chip) and at 72px (a card header), which ruled out anything with a chat
bubble or a tail — those turn to mush at chip size.

    python tools/make-default-avatar.py                 # writes assets/avatars/default.png
    python tools/make-default-avatar.py --svg-preview   # also dumps an SVG to compare
"""
from __future__ import annotations

import os
import sys

from PIL import Image, ImageDraw, ImageFont

SIZE = 256
SUPERSAMPLE = 4
TOP = (43, 58, 103)      # deep blue
BOTTOM = (24, 28, 42)    # near-black slate
INK = (240, 244, 255)    # glyph
ACCENT = (91, 155, 255)  # cursor


def font(size: int):
    """A monospace bold face, so `>` and `_` have the same advance."""
    for path in (r"C:\Windows\Fonts\consolab.ttf", r"C:\Windows\Fonts\consola.ttf",
                 r"C:\Windows\Fonts\DejaVuSansMono-Bold.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"):
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                continue
    return ImageFont.load_default()


def main() -> int:
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    out = os.path.join(root, "assets", "avatars", "default.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)

    big = SIZE * SUPERSAMPLE
    image = Image.new("RGBA", (big, big), (0, 0, 0, 0))

    # Vertical gradient, then clipped to a disc by the alpha mask.
    gradient = Image.new("RGBA", (1, big))
    for y in range(big):
        ratio = y / max(1, big - 1)
        gradient.putpixel((0, y), (
            int(TOP[0] + (BOTTOM[0] - TOP[0]) * ratio),
            int(TOP[1] + (BOTTOM[1] - TOP[1]) * ratio),
            int(TOP[2] + (BOTTOM[2] - TOP[2]) * ratio),
            255,
        ))
    disc = gradient.resize((big, big))
    mask = Image.new("L", (big, big), 0)
    ImageDraw.Draw(mask).ellipse([(0, 0), (big - 1, big - 1)], fill=255)
    image.paste(disc, (0, 0), mask)

    # Draw the mark on its own layer and centre its *ink*, not its text box: `>` and `_`
    # sit at opposite ends of the line box, so box-centring looks visibly crooked.
    glyph_font = font(int(big * 0.54))
    prompt, cursor = ">", "_"
    ink = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    ink_draw = ImageDraw.Draw(ink)
    prompt_w = ink_draw.textlength(prompt, font=glyph_font)
    gap = int(big * 0.02)
    baseline = big * 0.5
    ink_draw.text((0, baseline), prompt, font=glyph_font, fill=INK, anchor="ls")
    ink_draw.text((prompt_w + gap, baseline), cursor, font=glyph_font, fill=ACCENT, anchor="ls")

    box = ink.getbbox()
    offset = (int(big / 2 - (box[0] + box[2]) / 2), int(big / 2 - (box[1] + box[3]) / 2))
    image.alpha_composite(ink, dest=(max(0, offset[0]), max(0, offset[1])))

    image.resize((SIZE, SIZE), Image.LANCZOS).save(out)
    print(f"wrote {out} ({os.path.getsize(out)} bytes, {SIZE}x{SIZE})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
